import os
import datetime
import json
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.graphics.shapes import Drawing, Rect, String as DString, Line
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import VerticalBarChart

class PDFReportGenerator:
    @staticmethod
    def add_page_decorations(canvas, doc):
        """Draws page borders, headers, footers, and the requested confidential watermark."""
        canvas.saveState()
        
        # 1. Draw Watermark: "SOC Sentinel XDR" and "CONFIDENTIAL"
        canvas.setFont('Helvetica-Bold', 38)
        canvas.setFillColor(HexColor('#f1f5f9')) # Very light gray for watermark
        
        # Translate to page center and rotate 45 degrees
        canvas.translate(300, 400)
        canvas.rotate(40)
        canvas.drawCentredString(0, 30, "SOC SENTINEL XDR")
        canvas.drawCentredString(0, -20, "CONFIDENTIAL")
        
        # Restore translation matrix
        canvas.restoreState()
        canvas.saveState()
        
        # 2. Draw Header
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(HexColor('#64748b'))
        canvas.drawString(54, 750, "SOC Sentinel XDR - Incident Response Platform")
        canvas.drawRightString(558, 750, f"Generated: {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
        canvas.setStrokeColor(HexColor('#cbd5e1'))
        canvas.setLineWidth(0.5)
        canvas.line(54, 742, 558, 742)
        
        # 3. Draw Footer
        canvas.line(54, 60, 558, 60)
        canvas.drawString(54, 45, "Classification: RESTRICTED // INTERNAL SOC USE ONLY")
        canvas.drawRightString(558, 45, f"Page {doc.page}")
        
        canvas.restoreState()

    @classmethod
    def generate(cls, report, output_path):
        """Generates the PDF report and writes to output_path."""
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        
        # Page size setup
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=72,
            bottomMargin=72
        )
        
        styles = getSampleStyleSheet()
        
        # Custom Typography Styles
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=24,
            leading=28,
            textColor=HexColor('#0f172a'),
            spaceAfter=6
        )
        
        subtitle_style = ParagraphStyle(
            'ReportSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=11,
            leading=14,
            textColor=HexColor('#475569'),
            spaceAfter=20
        )
        
        h1_style = ParagraphStyle(
            'SectionH1',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=HexColor('#1e293b'),
            spaceBefore=16,
            spaceAfter=8,
            keepWithNext=True
        )
        
        body_style = ParagraphStyle(
            'ReportBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=13.5,
            textColor=HexColor('#334155'),
            spaceAfter=8
        )
        
        block_header_style = ParagraphStyle(
            'BlockHeader',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=10,
            leading=12,
            textColor=HexColor('#ffffff')
        )
        
        table_header_style = ParagraphStyle(
            'TableHeader',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=8.5,
            leading=11,
            textColor=HexColor('#334155')
        )
        
        table_cell_style = ParagraphStyle(
            'TableCell',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=8,
            leading=11,
            textColor=HexColor('#334155')
        )
        
        story = []
        
        # --- TITLE BLOCK ---
        story.append(Paragraph(report.title.upper(), title_style))
        story.append(Paragraph(f"REPORT TYPE: {report.report_type} | GENERATED BY: {report.creator.username if report.creator else 'System'} | DATE: {report.created_at.strftime('%Y-%m-%d %H:%M:%S UTC')}", subtitle_style))
        story.append(Spacer(1, 10))
        
        # --- EXECUTIVE SUMMARY ---
        story.append(Paragraph("1. EXECUTIVE SUMMARY", h1_style))
        exec_summary_text = report.executive_summary or "No executive summary provided."
        # Keep paragraph clean of html entities
        story.append(Paragraph(exec_summary_text.replace('\n', '<br/>'), body_style))
        story.append(Spacer(1, 15))
        
        # --- CHARTS SECTION ---
        story.append(Paragraph("2. VISUAL METRICS", h1_style))
        charts_data = report.charts_data
        
        # Add visual charts based on report charts_data
        if 'severity' in charts_data and charts_data['severity']:
            story.append(Paragraph("Alert Severity Distribution:", table_header_style))
            d_severity = cls.draw_severity_chart(charts_data['severity'])
            story.append(d_severity)
            story.append(Spacer(1, 10))
            
        if 'types' in charts_data and charts_data['types']:
            story.append(Paragraph("Alert Types Breakdown:", table_header_style))
            d_types = cls.draw_types_chart(charts_data['types'])
            story.append(d_types)
            story.append(Spacer(1, 10))
            
        if 'ips' in charts_data and charts_data['ips']:
            story.append(Paragraph("Top Attacking IP Addresses:", table_header_style))
            d_ips = cls.draw_ips_chart(charts_data['ips'])
            story.append(d_ips)
            story.append(Spacer(1, 10))
            
        if not any(k in charts_data for k in ['severity', 'types', 'ips']):
            story.append(Paragraph("No visual metrics available for this report type.", body_style))
            
        story.append(Spacer(1, 15))
        
        # --- FINDINGS SECTION ---
        story.append(Paragraph("3. KEY FINDINGS & ANALYSIS", h1_style))
        findings_text = report.findings or "No key findings available."
        story.append(Paragraph(findings_text.replace('\n', '<br/>'), body_style))
        story.append(Spacer(1, 15))
        
        # --- RECOMMENDATIONS ---
        story.append(Paragraph("4. MITIGATION & RECOMMENDATIONS", h1_style))
        recs_text = report.recommendations or "No recommendations provided."
        story.append(Paragraph(recs_text.replace('\n', '<br/>'), body_style))
        
        # Build Document
        doc.build(story, onFirstPage=cls.add_page_decorations, onLaterPages=cls.add_page_decorations)

    @staticmethod
    def draw_severity_chart(severity_data):
        """Draws native ReportLab Pie Chart of alert severities."""
        # severity_data is e.g. {'labels': ['Low', 'Medium', 'High', 'Critical'], 'counts': [5, 10, 3, 2]}
        d = Drawing(400, 160)
        
        labels = severity_data.get('labels', [])
        counts = severity_data.get('counts', [])
        
        pc = Pie()
        pc.x = 120
        pc.y = 10
        pc.width = 140
        pc.height = 140
        
        # Map values
        valid_data = []
        valid_labels = []
        valid_colors = []
        
        color_map = {
            'Low': HexColor('#3b82f6'),
            'Medium': HexColor('#eab308'),
            'High': HexColor('#f97316'),
            'Critical': HexColor('#ef4444')
        }
        
        for label, count in zip(labels, counts):
            if count > 0:
                valid_data.append(count)
                valid_labels.append(f"{label} ({count})")
                valid_colors.append(color_map.get(label, HexColor('#64748b')))
                
        if not valid_data:
            valid_data = [1]
            valid_labels = ['No Alerts']
            valid_colors = [HexColor('#e2e8f0')]
            
        pc.data = valid_data
        pc.labels = valid_labels
        
        for i, color in enumerate(valid_colors):
            pc.slices[i].fillColor = color
            
        d.add(pc)
        return d

    @staticmethod
    def draw_types_chart(types_data):
        """Draws native ReportLab Bar Chart of alert types."""
        # types_data is e.g. {'labels': ['Brute Force', 'IOC Match'], 'counts': [15, 3]}
        d = Drawing(450, 160)
        
        labels = types_data.get('labels', [])
        counts = types_data.get('counts', [])
        
        bc = VerticalBarChart()
        bc.x = 40
        bc.y = 25
        bc.height = 120
        bc.width = 380
        
        if not counts:
            counts = [0]
            labels = ['No Data']
            
        bc.data = [counts]
        # Truncate labels for space
        bc.categoryAxis.categoryNames = [l[:20] for l in labels]
        bc.categoryAxis.labels.boxAnchor = 'ne'
        bc.categoryAxis.labels.dx = 8
        bc.categoryAxis.labels.dy = -2
        bc.categoryAxis.labels.angle = -10
        bc.categoryAxis.labels.fontSize = 7
        bc.valueAxis.valueMin = 0
        bc.valueAxis.valueStep = max(1, int(max(counts) / 5)) if counts else 1
        bc.bars[0].fillColor = HexColor('#10b981') # green
        
        d.add(bc)
        return d

    @staticmethod
    def draw_ips_chart(ips_data):
        """Draws native ReportLab Bar Chart of source IPs."""
        d = Drawing(450, 160)
        
        labels = ips_data.get('labels', [])
        counts = ips_data.get('counts', [])
        
        bc = VerticalBarChart()
        bc.x = 40
        bc.y = 25
        bc.height = 120
        bc.width = 380
        
        if not counts:
            counts = [0]
            labels = ['No Data']
            
        bc.data = [counts]
        bc.categoryAxis.categoryNames = labels
        bc.categoryAxis.labels.boxAnchor = 'ne'
        bc.categoryAxis.labels.dx = 8
        bc.categoryAxis.labels.dy = -2
        bc.categoryAxis.labels.angle = -10
        bc.categoryAxis.labels.fontSize = 7
        bc.valueAxis.valueMin = 0
        bc.valueAxis.valueStep = max(1, int(max(counts) / 5)) if counts else 1
        bc.bars[0].fillColor = HexColor('#6366f1') # Indigo
        
        d.add(bc)
        return d
